version: '2'
services:
  db:
    image: postgres
  
  centralize:
    build: ./django_container
    image: app
    volumes:
    - ./django_container/virtualenv/centralize/:/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    command: bash -c "ls && python manage.py migrate && python manage.py runserver 127.0.0.1:8000"
